baseURL: /
languageCode: ru
defaultContentLanguage: ru
title: Konstantin Shibkov
theme: hugo-theme-stack
useRelativeCover: true
summaryLength: 20
paginate: 5
TableOfContents: true
enableRobotsTXT: false
deployment:
  matchers:
    - pattern: ^.+\.(js|css|svg|ttf)$
      cacheControl: 'max-age=18144000, no-transform, public'
      gzip: true
    - pattern: ^.+\.(png|jpg|woff2)$
      cacheControl: 'max-age=31536000, no-transform, public'
      gzip: false
    - pattern: ^.+\.(html|xml|json)$
      gzip: true
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true
params:
  defaultTheme: dark
  showReadingTime: false
  toc: true
  author: Shibkov Konstantin
  description: 'Статьи о java и linux, руководства и мануалы'
  lastModDisplay: '[your display text]'
  mainSections:
    - posts
  sidebar:
    compact: true
    avatar:
      enabled: true
      local: true
      src: img/ava.jpg
  widgets:
    page:
      - type: toc
  imageProcessing:
      cover:
        enabled: true
      content:
        enabled: false
  
taxonomies:
  tag: tags
languages:
  ru:
    params:
      title: Konstantin Shibkov - блог
      subtitle: 'Статьи о java и linux, руководства и мануалы'
      keywords: 'java, js, php, linux, manjaro, shibkov, spring'
      copyright: ''
      menuMore: Показать еще
      writtenBy: Автор
      readMore: Читать
      readOtherPosts: Другие записи
      newerPosts: В будущее
      olderPosts: В прошлое
      minuteReadingTime: мин на прочтение
      dateFormatSingle: 02.01.2006
      dateFormatList: 02.01.2006
      logo:
        logoText: sendel.ru
        logoHomeLink: /
    menu:
      main:
        - identifier: about
          name: Обо мне
          url: /about
          weight: -100
          params:
            - icon: about
        - identifier: shorts
          name: Shorts
          url: /shorts
          weight: 100
          params:
            - icon: ice-cream
        - identifier: books
          weight: 50
          name: Kниги
          url: /books
          params:
            - icon: book-2
